production:
  delivery_method: :smtp
  smtp_settings:
    enable_starttls_auto: true
    address: smtp.gmail.com
    port: 587
    authentication: :plain
    domain: "smtp.gmail.com"
    user_name: "julian.vasquez@netuxtecnologia.com"
    password: vaquerini662343

