production:
  delivery_method: :smtp
  smtp_settings:
    enable_starttls_auto: true
    address: "smtp.gmail.com"
    port: 587
    authentication: :plain
    domain: "smtp.gmail.com"
    user_name: "juvasquez88@gmail.com"
    password: vaquerini662343

