production:
  delivery_method: :smtp
  smtp_settings:
    enable_starttls_auto: true
    address: "74.125.140.109"
    port: 587
    authentication: :plain
    domain: "smt.google.com"
    user_name: "julian.vasquez@netuxtecnologia.com"
    password: vaquerini662343

